name: CI/CD Pipeline for Streamlit App

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests (if any)
        # Assuming you have a tests/ directory for your test cases

      # Run Streamlit app in headless mode, and kill after some time
      - name: Run training script
        run: |
          echo "Running training script..."
          python model/training.py

      # Run recommendation.py (generate recommendations)
      - name: Run recommendation script
        run: |
          echo "Running recommendation script..."
          python model/recommendation.py

      # Run prediction.py (make predictions)
      


      # (Optional) Run unit tests if needed
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          pytest tests/
      - name: Run Streamlit app
        run: |
          echo "Starting Streamlit app..."
          streamlit run streamlit_app.py --server.headless true &  # Run the app in the background
          sleep 10  # Wait for 10 seconds to let the app start
          echo "Streamlit app should have started."
          ps aux | grep streamlit  # Check if Streamlit process is running
          pkill -f streamlit  # Kill the Streamlit process after 10 seconds

      # MLflow logging test (for model logging)
      - name: MLflow logging test
        run: |
          python -c "
          from mlflow_utils.mlflow_logging import log_model, log_prediction
          from sklearn.dummy import DummyClassifier
          import pandas as pd
          
          # Dummy example for logging
          model = DummyClassifier(strategy='most_frequent')
          log_model(model, 'Dummy Model')  # Ensure this function is correctly defined in mlflow_utils
          input_data = pd.DataFrame({'feature1': [1], 'feature2': [0]})
          log_prediction(input_data, model.predict(input_data), 'Dummy Model')  # Ensure this function is correctly defined
          "
